name: Check Website for Changes

on:
  schedule:
    - cron: '0 0 */3 * *'

  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests

      - name: Check for Website Changes
        id: check
        run: python check_website.py

      - name: Create GitHub Issue
        # Run only if the previous step failed (exit code 1)
        if: failure()
        uses: peter-evans/create-issue@v4
        with:
          title: "Website Change Detected"
          body: |
            The content of the monitored website has changed.

            - URL: https://docs.sqd.dev/subsquid-network/participate/worker/ 
            - Timestamp: ${{ github.event.date }}

          labels: |
            website-monitoring
